### ISSUE TITLE
Layman config

### ISSUE THREAD

**Issue by xificurk** [mkyral/gentoo-overlay#1]
Ahoj,

mohl bys prosím přidat XML config pro layman? Něco ve stylu: https://raw.githubusercontent.com/xificurk/xificurk-gentoo-overlay/master/xificurk-overlay.xml

Nebo jsem něco zaspal a existuje způsob, jak overlay přidat nějak "pohodlně" i bez toho?

**Comment by mkyral** [comment]
No mrknu na to. Až tak daleko jsem se ještě nedostal :-D

**Comment by mkyral** [comment]
Stačí takto?

**Comment by xificurk** [comment]
:+1: díky
